name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deployFCB:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        run: echo "Hello World!"

      - name: listar
        run: ls -la